from typing import List, Optional
from enum import Enum

from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """Represents a chat message."""

    role: str  # "user" or "assistant"
    content: str  # The message content


class Language(str, Enum):
    ENGLISH = "en"
    MALAYALAM = "ml"


class TranslationRequest(BaseModel):
    text: str
    direction: str = Field(..., pattern="^(en-ml|ml-en)$")


class TranslationResponse(BaseModel):
    translated_text: str
    source_language: str
    target_language: str


class QueryRequest(BaseModel):
    """Represents a query request."""

    query: str
    language: Language = Language.ENGLISH
    chat_history: list = Field(default_factory=list)


class QueryResponse(BaseModel):
    """Represents a query response."""

    answer: str = Field(..., description="The final answer generated by the RAG pipeline.")
    retrieved_sources: list[str] = Field(default_factory=list, description="Sources of the retrieved documents.")
    rewritten_query: str | None = Field(None, description="The rewritten query after processing.")
    processing_time: float = Field(..., description="Time taken to process the query in seconds.")
    confidence_score: float = Field(..., description="Confidence score of the answer (0-1).")


class Token(BaseModel):
    access_token: str
    token_type: str


class TokenData(BaseModel):
    username: Optional[str] = None


class User(BaseModel):
    username: str
    disabled: Optional[bool] = None


class UserInDB(User):
    hashed_password: str
